### ISSUE TITLE
WhatsApp broken - "WhatsApp works with Google Chrome 36+"

### ISSUE THREAD

**Issue by redfellow** [wavebox/waveboxapp#1025]
* Wavebox Version: 4.9.7.beta
* Operating System & Version: Windows 10

**Steps to reproduce**
Add WhatsApp. Problem shows up instantly.

**Is the bug persistent or intermittent?**
Closed and re-opened Wavebox three times and tried re-adding. Same result.

**Screenshots**
![image](https://user-images.githubusercontent.com/1110164/57519962-30218c80-7325-11e9-95ff-df3c640a7574.png)

**Additional information**
Using Dark Reader, LastPass & Adblock extensions

**Comment by Thomas101** [comment]
Hi, this has been fixed in [4.9.8 beta](https://github.com/wavebox/waveboxapp/releases/tag/v4.9.8)

https://github.com/wavebox/waveboxapp/issues/1024

**Comment by redfellow** [comment]
Ah, I should have searched for closed issues as well. My bad 👍

**Comment by bkuri** [comment]
I'm still getting this error as of `v4.9.8beta`. Removing the account and adding it again works for a little while but returns eventually.

**Comment by Thomas101** [comment]
@bkuri updating to the latest version (4.10.1) should fix this. You may need to remove WhatsApp and re-add it again if the warning doesn't clear
