### ISSUE TITLE
Gitter Notifications Missing

### ISSUE THREAD

**Issue by pauby** [wavebox/waveboxapp#1081]
* Wavebox Version: 4.11.2
* Operating System & Version: [Windows 10
* Account type (if applicable): Gitter

**Expected & actual behavior**
Gitter notifications to appear in Wavebox either through the red square or a number.

**Steps to reproduce**
For me it's a matter of they don't appear.

**Is the bug persistent or intermittent?**
Persistent.

**Screenshots**
Not sure one would help :)

**Additional information**
At the moment I have 9 notifications in a room in Gitter. Wavebox does not show the red dot, number of anything else to indicate there are notifications waiting.

This seems related (actually identical) to #530

**Comment by Thomas101** [comment]
Thanks for reporting! I've pushed an update out to fix this which the app should grab at some point in the background. If not a restart will grab it manually :)

**Comment by pauby** [comment]
@Thomas101 Still no updated version of this available (I have tried to click Update as well as letting nature takes it's course - I'm on the Beta channel, should that make a difference?).

Can we reopen this until it is and the fix is confirmed?

**Comment by Thomas101** [comment]
I pushed the update over the wire, so it doesn't need a whole app update.

If you right-click on Gitter and to `Account Settings` scroll to the `About` section, does it say version 7?
<img width="519" alt="Screenshot 2019-08-27 at 08 48 57" src="https://user-images.githubusercontent.com/103586/63751624-a41d7b80-c8a7-11e9-97b6-fb1d43ca2910.png">

**Comment by pauby** [comment]
Ahh. Okay. I was waiting on 'a new version is available' message. It does indeed say 7 for Container Version. Apologies.

Unfortunately the notifications still do not appear.

**Comment by Thomas101** [comment]
Okay, I've pushed another update out so it should bump up to version 8 after a while/after a restart.

Is this any better? If not what does your gitter sidebar look like, e.g. 
<img width="433" alt="Screenshot 2019-08-28 at 09 51 15" src="https://user-images.githubusercontent.com/103586/63840728-77d22f80-c979-11e9-9cb3-e426529d30bf.png">

**Comment by pauby** [comment]
I can confirm I have Container version 8. However I'm no longer able to login. After the password page I get this:

![image](https://user-images.githubusercontent.com/12760779/63844223-596b3480-c977-11e9-8661-f1b5617fe74c.png)

Previously I would get the 2FA page to enter my code as I do have 2FA enabled on my GitHub account (which is what I'm using to login). In the browser I've logged out of GitHub and then back in again so my account is working and GitHub is working.

**Comment by Thomas101** [comment]
Weird, I've just tried that here and it signs me in okay. Try removing Gitter and adding it again - could just be a glitch with Github as the `sessions/two-factor` url definitely exists

**Comment by pauby** [comment]
> Try removing Gitter and adding it again

Apologies. I did that first. I forgot to say.

**Comment by Thomas101** [comment]
I'm still not seeing it here :-(. Seems to sign in me in right away.

Did you attach your new Gitter to an existing group or just via the big add button in the bottom left?

**Comment by pauby** [comment]
Here's what I did:

* Added it to the existing account it was in before whcih didn't work;
* Added it as a separate account and it works. 
* Removed it from both and restarted Wavebox;
* Added it back in to the existing account and it still didn't work.
* Ticked 'Sandbox Service' and it works;

The account didn't need to be sandboxed before but as long as it works now that is the main thing. I also now see:

![image](https://user-images.githubusercontent.com/12760779/63848924-65a7bf80-c980-11e9-8bb3-87c0c6513d8b.png)

😄

**Comment by Thomas101** [comment]
> Added it to the existing account it was in before whcih didn't work;

That's because removing it and adding it doesn't actually wipe data when doing this (all the tabs share the same sandbox). If you don't want to sandbox it, then `Account Settings` > `Tools` > `Clear All Browsing Data` should work. That said, if you're happy with it sandboxed I don't see any reason why it shouldn't work :)

**Comment by pauby** [comment]
> If you don't want to sandbox it, then Account Settings > Tools > Clear All Browsing Data should work.

That didn't work. I've had to keep 'Sandbox Service'.

Thinking about it, why would I need to clear it? If I'm logging in using exactly the same details as before?

**Comment by Thomas101** [comment]
I was thinking along the lines that there was some stale data, either from cookies/cached resources that could be the cause of the problem :)

**Comment by pauby** [comment]
Ah. Cool. Unfortunately not though 😭
