### ISSUE TITLE
Slack threads do not show the unread indicator, clicking notifications takes you to the main channel

### ISSUE THREAD

**Issue by normalspark** [wavebox/waveboxapp#1393]
* Wavebox Version: 10.104.7.2 stable
* Operating System & Version: Mac OSX 12.5.1
### Bug/Feature description
The unread indicator appears for messages in channels, but does not appear when there are unread messages in threads.

When a desktop notification is received for a message in a slack thread, clicking the notification correctly switches to the slack app, but takes you to the main channel that contains the thread, rather than the thread itself.

### Steps to reproduce (if applicable)
Receive a message in a slack thread.
Note that the unread indicator does not appear on the slack app.

When a desktop notification for a message is received, click the notification. Note that the slack app appears but navigates to the main channel containing the thread, instead of the thread itself.

**Comment by Thomas101** [comment]
Hi, thanks for reporting. I've just pushed a config update out with a fix for this. Wavebox will grab this automatically, but if you want to force it...

1. Go to Settings > About. Press check for updates
2. Wavebox may report there are no updates available, but will fetch a fresh config
3. Slack should now report the counts properly

Let me know if this fixes it for you!

**Comment by normalspark** [comment]
Thanks for the fast reply!

Looks good on my end, thanks so much!

**Comment by normalspark** [comment]
Hi @Thomas101.

Thanks for the fast response.

Can confirm the unread indicator now works correctly for the threads, thanks for the fix! 

Looks like we still have the issue where clicking the desktop notification when receiving a message in a thread still takes you to the channel containing the thread, rather than the thread itself.
