### ISSUE TITLE
Windows 10 notifications in Action Center

### ISSUE THREAD

**Issue by Thomas101** [wavebox/waveboxapp#140]
Notifications don't stay in the action center after being shown

https://github.com/electron/electron/issues/3916

**Comment by nmat** [comment]
Checking the upstream issue on electron it seems they have closed it without reference to any other issue. I wonder if this is actually fixed in the upcoming version of electron that is going to be used in wavebox?

**Comment by Thomas101** [comment]
It looks like they've just closed it for housekeeping. Given a try with 2.0.0 and it's still present. Will see if they'll re-open
