### ISSUE TITLE
Missing window control buttons on Linux Chrome when maximized

### ISSUE THREAD

**Issue by WebShapedBiz** [wavebox/waveboxapp#322]
* Which version of Wavebox are you using? [e.g. 3.0.0]
Version 3.1.16beta

* Which Operating System are you using? [e.g. Windows 10, Mac OSX 10, Ubuntu 14.04]
Elementary OS Loki 0.4.1.

Quite odd, when I open a link from Wavebox in my default browser Chrome, and I want to maximize the Chrome window, the window control buttons disappeared.

This is not happening when the Chrome is already open and Wavebox opens a new tab.

Screenshot: [http://screencloud.net/v/aIlIy](http://screencloud.net/v/aIlIy)

**Comment by Thomas101** [comment]
Hi, thanks for reporting. I'll see if I can find any mention of this upstream and if not raise it. It would be great to know how you installed Wavebox (snap, deb, repo, tar) and if you open the terminal and type `xdg-open "https://wavebox.io"` does the opened window exhibit the same behaviour?

**Comment by WebShapedBiz** [comment]
Hi Thomas, nice to hear from you.

- this issue is present on installation from repository and from def file
(beta) from github.
- the screencast is made with the beta version.
- opening Chrome with xdg-open is resulting in normal behaviour.
- you can see all the behaviors in this screencast: https://goo.gl/5vfp4N

Cheers.

Best regards,

Sinisa Perovic
WebShaped.biz

Web: http://www.webshaped.biz
E-Mail: sinisaperovic@webshaped.biz
SkypeID: sinisaperovic
Telegram: @sinisaperovic

2017-07-25 11:39 GMT+02:00 Thomas Beverley <notifications@github.com>:

**Comment by Thomas101** [comment]
Thanks very much for the screencast. That's immensely helpful! I've managed to reproduce it my end and opened an issue upstream (https://github.com/electron/electron/issues/10134). Would you mind if I post your screencast there? Might help someone else diagnose!

**Comment by WebShapedBiz** [comment]
Post away Thomas. I'm glad that I can help a little to both Electron and
Wavebox.

Best regards,

Sinisa Perovic
WebShaped.biz

Web: http://www.webshaped.biz
E-Mail: sinisaperovic@webshaped.biz
SkypeID: sinisaperovic
Telegram: @sinisaperovic

2017-07-27 10:10 GMT+02:00 Thomas Beverley <notifications@github.com>:

**Comment by Thomas101** [comment]
Awesome thank you!

**Comment by Thomas101** [comment]
@WebShapedBiz I've just given this a try with version 62 of chrome and have noticed that the default behaviour with chrome now seems to be that the buttons are always hidden, irregardless of how it was opened. Are you seeing the same? I'm wondering if this is a design decision by Google :-/

**Comment by WebShapedBiz** [comment]
That's a bug, should be fixed in version 63.

**Comment by Thomas101** [comment]
Yeah, I can confirm that beta the beta. Original issue still seems to persist.

**Comment by WebShapedBiz** [comment]
Yes, on Elementary OS Juno (Ubuntu 18.04 based), Google Chrome 70.0.3538.102 and Wavebox 4.4.0 this is still an issue in the same way that was originally reported.
