### ISSUE TITLE
whats new (when there is new items) does not show up any news ever

### ISSUE THREAD

**Issue by nmat** [wavebox/waveboxapp#439]
* Which version of Wavebox are you using?
3.4.3 beta

* Which Operating System are you using?
windows 10

* Description:
I have set the whats new to be: when there is new items

However come to think of it I have not yet seen any notification or anything about there being a new items in "whats new" since I set this behaviour. Is this correct or how should the behaviour act?

**Comment by Thomas101** [comment]
That's our fault, we've been a bit forgetful in pushing the notification out. Expect one early next week when 3.5.0 stable ships ;-)

**Comment by nmat** [comment]
I am going to close this because it works on both beta and stable now. Seen it work just fine.

thank you

**Comment by nmat** [comment]
This seems broken again. I can see there is blog posts about news but nothing has come up in client. :(

**Comment by nmat** [comment]
Wavebox version: 3.7.0 stable

**Comment by Thomas101** [comment]
Writing the news fell off the bottom of a long list yesterday. Should be updated now ;-)

**Comment by Thomas101** [comment]
Going to close this off again - I think we pushed an update out when the stable happened :)

**Comment by nmat** [comment]
I am going to reopen this since it still does not seem like the 22 of march blog post of news came up in wavebox from latest 3.xx release. I noticed it when visiting the website and have the setting set to "when there is new items" set.

Since I love to see the new posts and keep updated on the wavebox app and the news it would be good to have this working :)

**Comment by Thomas101** [comment]
That's our fault. I got Susan checking the 1000 sites we added rather than writing the news. It should be up now!
