### ISSUE TITLE
Some weirdness with Mixmax extension.

### ISSUE THREAD

**Issue by GollyJer** [wavebox/waveboxapp#460]
* Which version of Wavebox are you using?
**3.5.1 beta**

* Which Operating System are you using? [e.g. Windows 10, Mac OSX 10, Ubuntu 14.04]
**Windows 10**

When using the Mixmax extension (THANKS for implementing this one by the way) it works great in the compose window, but the lightning bolts to opens are missing.  Also, all settings screens are empty.

This screenshot shows both issues.
![2017-11-08_16h48_28](https://user-images.githubusercontent.com/689204/32576669-8dd18590-c4a5-11e7-9292-50942b3e7af5.png)

**Comment by Thomas101** [comment]
Thanks for reporting. The empty settings screen I've seen - we've got a fix for this ready to land in 3.5.2beta.

As for the lightning bolts, they appear to be there when we've been testing. If you try sending a fresh email does a lightning bolt appear next to that one? If you try restarting Wavebox does that work? Finally how many Google accounts do you have added?

**Comment by GollyJer** [comment]
I have a Google Inbox account (primary, the one from the screenshot) and a Gmail account.

**Comment by dchersey** [comment]
Hi @Thomas101 I wanted to add that mixmax is working fairly well for me in the actual message compose window (I am using 3.5.0 on MacOS 10.12.6) but when I go to insert calendar availability (/cal) or group event availability, the dialog pops up, everything works in terms of selecting times, but the "insert times" button (which populates the email with the mixmax-extended content; i.e the point of the whole thing) does not do anything; the dialog stays up and there is no new content inserted into the email. 

I compared this to how it works in Chrome with the extension installed directly, and MixMax is working correctly for me there. 

Thanks for your help, and I'm happy to beta-test any possible fixes.

David

**Comment by Thomas101** [comment]
@dchersey the root of that bug is the same as the blank window above. We've got a fix for that one due to land in the next beta. We we're hoping to ship last week but have been held up by a few technical problems

**Comment by Thomas101** [comment]
Hi, we’ve just released a fix for this to the beta channel of Wavebox in version 3.5.2. If you want to give it a try there are some instructions on [how to use the beta channel here](https://wavebox.io/kb/beta-channel). Thanks

**Comment by Thomas101** [comment]
@dchersey I think the calendar availability is still an issue in the current beta. I'll keep this issue open for the meantime to make sure we get that working!

@GollyJer the blank window should be fixed, I think the missing read notifications should be fixed in this one too

**Comment by dchersey** [comment]
That is correct @Thomas101, the insert times button still does not do anything.  I can do everything else on that popup except complete the process :(

Thanks for your help & let me know when you want me to test it again.

**Comment by dchersey** [comment]
Any updates on which beta might address this? Just tried 3.6.2 but no dice :(

**Comment by GollyJer** [comment]
Update on my end... **3.6.2beta**
- MixMax popups now show the correct content.
- Lightning bolts still missing.

If I'm on the Sent folder in Inbox, then `reload` the page in wavebox then the bolt shows up.  If I then navigate to the Inbox and back to Sent the bolts are gone.

Not sure if that helps... but at least it's something.

**Comment by Thomas101** [comment]
It will be 3.6.3 beta

**Comment by dchersey** [comment]
FYI @GollyJer I have bolts in both my sent boxes; no reloading required.

**Comment by GollyJer** [comment]
@dchersey Are you using `Gmail` or `Inbox by Gmail`?

**Comment by Thomas101** [comment]
@GollyJer we've been trying to figure out what's going on here. We added Mixmax to a fresh user profile on Chrome and tested the following to see what the difference was between Chrome and Wavebox.

In our testing we've seen some sporadic results with showing the bolts in Chrome, with the same outcomes on both Gmail and Google Inbox, it would be good to know if you're seeing the same.

See no bolts
1. Load mail.google.com or inbox.google.com
2. Wait 5 - 10 seconds for everything to fully load
3. Switch to sent mail
4. See no bolts

See bolts when loading directly into sent folder
1. Load https://mail.google.com/mail/u/0/#sent or https://inbox.google.com/u/0/sent
2. See bolts load after a few seconds

See bolts when quickly switching to sent folder
1. Load mail.google.com or inbox.google.com
2. Switch to sent mail as quickly as possible
3. See bolts load after a few seconds

If we try the steps in the first group, no matter how many times we try switching to sent, sending e-mails, navigating around or anything we can think of the bolts don't appear.

**Comment by GollyJer** [comment]
@Thomas101 Yup.  You're right.  It's on MixMax's end.

**Using Inbox in Chrome Browser...**
I see no bolts following your first process.
Your second and third process are basically the same. If you're in the Sent folder before the plugin fully loads then the bolts appear.  However, navigate to any other folder and they disappear.

**Comment by dchersey** [comment]
Hi @Thomas101, I've been out for a bit but just got back and downloaded 3.6.5 beta ... the mixmax dialogs (/cal, /availability) still do not let me hit the "Insert Times" button and populate the emails. 

Using Inbox to answer @GollyJer's question; and everything works fine in Chrome natively just not with Wavebox.

**Comment by dchersey** [comment]
Hi @Thomas101 this is still an issue with 3.10 ... any updates on a fix? Thank you :)

**Comment by Thomas101** [comment]
So the crux of the issue is the way electron handles new windows. It differs slightly from the way that Chrome does. For the most part things just work, but in this instance, it breaks the cross window chatter that MixMax uses to set the calendar availability.

In Decemeber we started to upgrade Wavebox from the Electron 1.7 branch to the 1.8 branch and as part of this started to put a fix together to make the window behaviour more closely match that of Chromes. We've had some success, but managed to break a bunch of other things in the process. In addition to this 1.8 has been a pain because the upgraded version of Chromium has a number of breaking changes which is causing a knock on effect for other things.

Looking forward though, we're really keen to fix this as its the cause of a few other issues too. In the new beta cycle of Wavebox (3.10.1->3.10.*) our aim is to move over to the electron 1.8 branch and as part of this fix the window open issue too. I'll keep the issue posted with any progress/updates and hopefully we can get this fixed soon

**Comment by Thomas101** [comment]
Hi, we’ve just released this to the beta channel of Wavebox in version 3.10.4. If you want to give it a try there are some instructions on [how to use the beta channel here](https://wavebox.io/kb/beta-channel). Thanks

**Comment by GollyJer** [comment]
@Thomas101 
The pop-up now works as expected... thanks!
The lightning bolts are still hit or miss but as discussed earlier it's on MixMax's end.

Best!
Jeremy

**Comment by dchersey** [comment]
Working for me!  I haven't tested it extensively, but that main thing is that I can dismiss the popup and it inserts mixmax functionality.  Very excited about exploring the capabilities of this plugin now that I can use it without logging into google (i.e. in a proper desktop app).

**Comment by Thomas101** [comment]
Hi, this has just been released in the latest version of Wavebox. You can get the update by using the Application/File menu and clicking `Check for Update` or by downloading the latest version from our [download page](https://wavebox.io/download). Thanks!
