### ISSUE TITLE
Notification incorrect with o365

### ISSUE THREAD

**Issue by huangv22** [wavebox/waveboxapp#47]
Notifications are not the same between unread in office365 vs. the notification badge in wavebox:

Refer to attached image: 
https://www.evernote.com/l/AAQESfP1l0FPeoW0xkL66_8-3sXUukGuTzc

Expected it to be 4
Actual: says 6

* Which version of Wavebox are you using? [e.g. 3.1.2]
* Which Operating System are you using? [e.g. Windows 10, **Mac OSX 10**, Ubuntu 14.04]

**Comment by jacksarick** [comment]
I had a similar problem, and realized that it was my settings in O365. It could also be that the account hasn't reloaded recently. To reload: right click on account icon > Reload

O365 inbox is counting unread messages in just the tab that it is set to watch. Wavebox is set to count ALL unread messages that haven't been filed. To fix it I adjusted my filters to show the actual amount of unread messages.

**Comment by Thomas101** [comment]
Wavebox runs a query for unread messages in your inbox. Would you be able to check this through the O365 search pane, by using the search term `isread:false` and then selecting the inbox folder.

![screen shot 2017-04-11 at 09 20 40](https://cloud.githubusercontent.com/assets/103586/24899429/2772f97c-1e98-11e7-923d-f3259365777a.png)

**Comment by huangv22** [comment]
Bug is no longer happening.

**Comment by huangv22** [comment]
Bug is happening again.

Please refer to image. 
searched for ````isread:false````
Does not show any unread messages

Account in Wavebox shows a 4 in both left navi and menu bar

<img width="480" alt="item-0_and_item-0_and_item-0" src="https://cloud.githubusercontent.com/assets/4745333/24978716/833d5ee8-1f86-11e7-85d2-4c6b0d8cc0a2.png">


@jacksarick , where are the settings in o365? Wanted to check that as well, but wasn't able to find th esetting.

**Comment by Thomas101** [comment]
If you right click on the account in the left and pick resync does this change it? (just wondering if the auto sync has fallen over for some reason)

**Comment by Thomas101** [comment]
Someone else reported some issues with outlook #50 and it looks like Microsoft have been having some trouble. If you restart Wavebox and go to View > Developer Tools & click the console tab do you see any errors coming out like they were?

**Comment by huangv22** [comment]
Restync did not resolve
Restarting wavebox did resolve the issue.

Per your instructions: Failed to load resource: the server responded with a status of 404 (Not Found)

**Comment by Thomas101** [comment]
Thanks, the 404 is probably your account icon. It looks like it's fallen back to the default one.

I'll add some debugging flags into the next build so we can pick out if it's running in the background or failing for some reason. After you restarted did it continue to run?

**Comment by Thomas101** [comment]
Hi, I've just pushed 3.1.6 out. Would you be able to give it a try to see if the unread count is accurate again? If not could you go to View > Developer Tools & click on the console tab again. This time type...

```js
window.waveboxDebug.tests.fetchMicrosoftUnreadMessageList()
```

You should see a log similar to the following which lists the unread messages...

![screen shot 2017-05-04 at 13 21 30](https://cloud.githubusercontent.com/assets/103586/25703265/bff64456-30cc-11e7-9d45-08b02706518c.png)

Are there any erroneous messages that shouldn't be there?

---

You can download the latest release from [wavebox.io/download](https://wavebox.io/download) or Wavebox should update itself over the next day or so. Thanks!

**Comment by jaisongreen** [comment]
This issue is still happening in 3.1.8.

**Comment by huangv22** [comment]
Hi @Thomas101, just checked again. Agree with @jaisongreen , it's still happening in 3.1.8

![developer_tools_and_wavebox__36_](https://user-
images.githubusercontent.com/4745333/27348241-35cf571c-55a8-11e7-88a2-e51d7a02f924.png)

**Comment by Thomas101** [comment]
There's a fix that's going in to 3.1.9 that fixes a bug where after a sync fails once it fails to sync again until restarting Wavebox. This might fix the issue. If you want to try it out beforehand I’ve put a early build of  Wavebox macOS [here](https://wavebox.io/dl/builds/Wavebox_3_1_8_7cb64a8_osx.dmg). Just a couple of things to bare in mind:
* To install just drag over the previous version of Wavebox.
* When the next version is released this version will update automatically as usual
* If you want to go back to the currently released version of Wavebox, go to the [Downloads Page](https://wavebox.io/download), download and install over the version you’ve updated

If you do try that build, it would be great to hear if it fixes the issue

**Comment by Thomas101** [comment]
@jaisongreen @huangv22 Wavebox 3.1.9 has just been released which includes a fix for this. Has it started working correctly for you?

**Comment by huangv22** [comment]
So far so good. Will re-open if it happens again

**Comment by Thomas101** [comment]
Awesome, will close this for now then :)
