### ISSUE TITLE
Switching window focus to previous browser window does not focus content

### ISSUE THREAD

**Issue by nmat** [wavebox/waveboxapp#477]
* Which version of Wavebox are you using?
3.5.2beta

* Which Operating System are you using?
Windows 10
Chrome

* Description:
Open a file in a new window (pdf for example) from google drive. (so it opens in a new wavebox browser window).
Switch to main wavebox window and for example switch to a different account
Go back to the previous opened pdf window using Alt+Tab
Try using the arrow keys to scroll down the pdf doc

* What happens:
Focus is being held on the outer part of the window and not the content. You have to manually click inside the window to get the pdf focus. If you don't you can't scroll

* What should happen (IMO):
Focus should go directly to content. This way you can use keyboard to navigate and minimize the use of using the mouse.

If someone else could verify this it would be perfect.

**Comment by nmat** [comment]
On another note. I noticed the same effect from choosing the window from the taskbar.

**Comment by Thomas101** [comment]
I think this is a bug. I've got some work I want to do on the content window in the next milestone, so I'll make sure this is working too

**Comment by Thomas101** [comment]
Whoops, got my issue numbers mixed up... https://github.com/wavebox/waveboxapp/commit/1a4ae3d784b7eb7bfbd5115a491cc6fba15bb451

**Comment by nmat** [comment]
verified and working in GIT

**Comment by Thomas101** [comment]
Hi, we’ve just released this to the beta channel of Wavebox in version 3.6.2. If you want to give it a try there are some instructions on [how to use the beta channel here](https://wavebox.io/kb/beta-channel). Thanks

**Comment by nmat** [comment]
Verified on beta channel in 3.6.2beta

tested on windows 10
and on macOS 10.13.2

**Comment by nmat** [comment]
I am noticing a some sporadic non focusing when it comes to switching to the external window.

This does not always happen but is rather sporadic. Still can't find a baseline for when it happens.

I started to work with bash on ubuntu on windows and switched back to a pdf doc in a external window and still the content was not selected. Will continue testing this a bit more. However in general the content is selected more often then not.

**Comment by nmat** [comment]
Managed to replicate it rather easy actually.

**Please test the below:**
1. Open a pdf from google drive in external window
2. Go to gmail inbox and click on the search field so that search field have focus
3. Ctrl+Tab back to the external window where PDF is viewed

The focus seems to be in the background instead of the content of the pdf. So when clicking the PDF white background then it will focus and I can arrow up and down in the doc. Is this intentional?

**Comment by nmat** [comment]
Closing again. In latest windows 10 release I do not see this issue. Will continue investigating

**Comment by Thomas101** [comment]
Hi, this has just been released in the latest version of Wavebox (3.7.0). You can get the update by using the Application/File menu and clicking `Check for Update` or by downloading the latest version from our [download page](https://wavebox.io/download). Thanks!
