### ISSUE TITLE
Option to use Roboto font for UI instead of Noto

### ISSUE THREAD

**Issue by pioneer** [wavebox/waveboxapp#507]
* Which version of Wavebox are you using? [e.g. 3.6.5-1]

* Which Operating System are you using? [Ubuntu 16.04 / Mint 18.3]

Before some version, Wavebox used Roboto font for UI, which fit very well into my desktop settings. Now it has changed to Noto. It'd be great to have an option to switch Roboto back.

**Comment by Thomas101** [comment]
Hi, we’ve just released the ability to add custom css to the main Wavebox window. You can find this under the `Main Window Custom CSS` button in Advanced settings. If you want to change the font to Roboto, Times or Arial, that's the place to do it!

This is in the beta channel of Wavebox in version 3.7.1 at the moment. If you want to give it a try there are some instructions on [how to use the beta channel here](https://wavebox.io/kb/beta-channel). Thanks

**Comment by Thomas101** [comment]
Hi, this has just been released in the latest version of Wavebox (3.8.0). You can get the update by using the Application/File menu and clicking `Check for Update` or by downloading the latest version from our [download page](https://wavebox.io/download). Thanks!

**Comment by pioneer** [comment]
Still doesn't work for me, have a look at the screenshot attached

![_088](https://user-images.githubusercontent.com/200538/34946642-55d4affa-fa10-11e7-984b-2f0acfe93827.png)

**Comment by Thomas101** [comment]
You're going to need to be more specific with your selector.... `html, body, *:not(.material-icons):not(.font-awesome)`

Then if you don't have Roboto installed on your system, you will need to pull this in from somewhere... E.g. pasting the contents of the [google fonts stylesheet](https://fonts.googleapis.com/css?family=Roboto:100,100i,300,300i,400,400i,500,500i,700,700i,900,900i) in first

**Comment by pioneer** [comment]
It works now, but only partly - the tabs' font has changed, but not the UI switches' font etc. Any ideas how to tweak the selector?

![_089](https://user-images.githubusercontent.com/200538/34949013-7e7dd632-fa17-11e7-81ea-7e6d0573c350.png)

**Comment by Thomas101** [comment]
Sorry, forgot to say add an `!important` on the end of the style

**Comment by pioneer** [comment]
Yeah, it works nicely now, thanks. So this issue can be closed with maybe keeping in mind to ease such simple tasks in future.
