### ISSUE TITLE
macOS: Changing translucent sometimes triggers crash dialog on restart

### ISSUE THREAD

**Issue by nmat** [wavebox/waveboxapp#696]
* Wavebox Version: 3.14.7beta
* Operating System & Version: macOS
* Account type (if applicable): None

**Expected & actual behavior**
Normal restart of application.

Sometimes triggers crash dialog (still does change the expected setting but is confusing due to crash dialog)

**Steps to reproduce**
Keep changing the setting for translucency. It will on restart of app trigger crash dialog.

**Is the bug persistent or intermittent?**
Seems to be on every once or while changing the setting on restart of app.

**Comment by Thomas101** [comment]
Yeah I get it. Took me a few attempts and it took forever for the crash to come up.

Seems to only be with translucency - none of the other restart settings

**Comment by Thomas101** [comment]
Hi, we’ve just released this to the beta channel of Wavebox in version 3.14.8. If you want to give it a try there are some instructions on [how to use the beta channel here](https://wavebox.io/kb/beta-channel). Thanks

**Comment by nmat** [comment]
I am still getting the crash on beta on macOS when I changed from Dark -> Ultra Dark 

Also got the crash dialog on Ultra Dark -> None

None -> Light - No crash dialog
None -> Medium Light - No crash dialog
None -> Dark - No crash dialog
None -> Ultra Dark - No crash dialog

Light -> None - Crash dialog
Medium Light -> None -> Crash dialog
Dark -> None -> Crash dialog
Ultra Dark -> None - Crash dialog

Ultra Dark -> Dark -> Crash dialog

It seems almost like going from None to another setting works without getting the warning. But when switching inside any of the others to another creates the dialog.

**Comment by nmat** [comment]
Noticed also that quiting wavebox when a translucency is active gives the same crash dialog. When None is selected no crash dialog occurs. (everything is working fine in general and the dialog is only a warning but could cause people to think that wavebox is malfunctioning) :/

**Comment by Thomas101** [comment]
Yeah I'm seeing the same. It takes a little time for the crash to come up which is probably why I thought I'd fixed it.

I think this a problem with electron - I'll re-add the experimental flag to the setting for the time being

**Comment by Thomas101** [comment]
Fixed in the electron 3 upgrade

**Comment by nmat** [comment]
Verified and working on git master this can be closed on next beta

**Comment by Thomas101** [comment]
Hi, we’ve just released this to the beta channel of Wavebox in version 4.4.2. If you want to give it a try there are some instructions on [how to use the beta channel here](https://wavebox.io/kb/beta-channel). Thanks

**Comment by Thomas101** [comment]
Hi, this has just been released in the latest version of Wavebox (4.5.0). You can get the update by using the Application/File menu and clicking `Check for Update` or by downloading the latest version from our [download page](https://wavebox.io/download). Thanks!
